// client/src/app/products/[productId]/page.tsx

"use client";

import React, { useState } from "react";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { useParams } from "next/navigation";
import {
  useGetProductByIdQuery,
  useGetVariantsByProductIdQuery,
} from "@/state/api";
import BuyingOptions from "@/components/common/BuyingOptions";

const ProductsPage = () => {
  const { productId } = useParams(); // 1. Component initializes by using the useParams to extract the productId from the URL

  {
    /* State hooks defined to keep track of the color and size selected by the user. */
  }
  const [selectedColor, setSelectedColor] = useState<string | null>(null);
  const [selectedSize, setSelectedSize] = useState<string | null>(null);

  const {
    data: product,
    error: productError,
    isLoading: productLoading,
  } = useGetProductByIdQuery(productId as string);

  // Move mainImage state here, after product is fetched
  const [mainImage, setMainImage] = useState(product?.imageURL || "");

  console.log("Product Detail Page Product ID: ", productId);

  {
    /* 2. API Queries called with productId to retrieve the product details and variants */
  }
  // Fetch variants using the product variants
  const {
    data: variants,
    error: variantsError,
    isLoading: variantsLoading,
  } = useGetVariantsByProductIdQuery(productId as string);

  if (productLoading || variantsLoading) return <div>Loading...</div>;
  if (productError) return <div>Error loading product</div>;
  if (variantsError) return <div>Error loading product variants</div>;

  if (!product) {
    return <div>Product not found</div>;
  }

  if (!variants) {
    return <div>Product variants not found</div>;
  }
  console.log("Product: ", product);
  console.log("Product Variants: ", variants);

  {
    /*
     * 3. Displaying product information: product name, price, and description are displayed using Image
     * Unique Colors and Unique Sizes arrays are generated by mapping over the variants data and extracting
     * unique color and size options.
     */
  }
  const uniqueColors = Array.from(new Set(variants.map((v) => v.color)));
  const uniqueSizes = Array.from(new Set(variants.map((v) => v.size)));

  {
    /*
     * 4. User interaction for selecting color and size
     */
  }
  const handleColorSelect = (color: string) => {
    console.log("Selected color:", color);
    setSelectedColor(color);
  };

  const handleSizeSelect = (size: string) => {
    console.log("Selected size:", size);
    setSelectedSize(size);
  };

  {
    /*
     * 5. The selectedVariant is determined by finding a variant in variants that
     * Filter the correct variant based on selected size and color
     */
  }
  const selectedVariant = variants.find(
    (variant) =>
      variant.size === selectedSize && variant.color === selectedColor,
  );

  const handleThumbnailClick = (image: string) => {
    setMainImage(image);
  };

  return (
    <div className="flex flex-col space-x-8 md:flex-row">
      {/* Product Image Gallery */}
      <div className="flex flex-row space-x-4">
        {/* Thumbnails on the left */}
        <div className="flex flex-col space-y-2">
          {product.imageURL2.map((image, index) => (
            <Image
              key={index}
              src={
                image ||
                "https://s3-cakedenim.s3.us-west-1.amazonaws.com/cakebabe.png"
              }
              alt="Thumbnail"
              width={100}
              height={150}
              className="cursor-pointer hover:opacity-80"
              onClick={() => handleThumbnailClick(image)}
            />
          ))}
        </div>

        {/* Main image */}
        <Image
          src={mainImage || product.imageURL}
          alt={product.name}
          width={600}
          height={800}
        />
      </div>

      {/* Product Details */}
      <div className="flex-1">
        <h1 className="text-lg">{product.name}</h1>
        <p className="mt-4 text-2xl text-gray-700">${product.price}</p>

        <p className="mt-2 text-sm text-gray-500">
          Pay as low as <strong>$70/mo</strong> with Klarna, or{" "}
          <strong>$103.65/mo</strong> with Afterpay.
        </p>
        <p className="mt-6">{product.description}</p>

        {/* Color Selection */}
        <div className="mt-4">
          <h3 className="text-lg font-semibold">Color</h3>
          <div className="mt-2 flex space-x-2">
            {uniqueColors.map((color, index) => (
              <button
                key={index}
                className={`h-8 w-8 rounded-full border ${
                  selectedColor === color ? "border-black" : "border-gray-600"
                }`}
                style={{ backgroundColor: color }}
                onClick={() => handleColorSelect(color)}
              />
            ))}
          </div>
        </div>

        {/* Size Selection */}
        <div className="mt-4">
          <h3 className="text-lg font-semibold">Size</h3>
          <div className="flex flex-wrap gap-2">
            {uniqueSizes.map((size, index) => (
              <Button
                key={index}
                variant="link"
                size="sm"
                type="button"
                className={`text-md rounded p-2 ${
                  selectedSize === size ? "bg-gray-400 text-white" : ""
                }`}
                onClick={() => handleSizeSelect(size)}
              >
                {size}
              </Button>
            ))}
          </div>
        </div>

        {/* 6. Adding to Cart using the Add to Bag Button */}
        <div className="mt-6 flex flex-row space-x-2">
          <BuyingOptions
            product={product}
            variantId={selectedVariant?.variantId ?? null}
            color={selectedColor}
            size={selectedSize}
          />
        </div>
      </div>
    </div>
  );
};

export default ProductsPage;
